default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: robert
  password: postgres
development:
  <<: *default
  database: cropconnect_development
test:
  <<: *default
  database: cropconnect_test
production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
